name: WebdriverIO-tests with docker

on:
  push:
    branches:
      - master
jobs:
  test-wdio:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16.x'
      - name: Install
        run: npm install

      - name: Run docker-compose
        run: docker-compose up -d

      - name: Tests 
        continue-on-error: true
        run: npm run test

      - name: Generate Report
        if: always()
        run: npm run allure-report-generate             
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: allure-report
            path: allure-report/

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
             ref: gh-pages
             path: gh-pages        
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
             allure_results: allure-results
             gh_pages: gh-pages
             allure_report: allure-report
             allure_history: allure-history
             keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
             PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             PUBLISH_BRANCH: gh-pages
             PUBLISH_DIR: allure-history
        
         
  
          
